# Generated by Django 4.0 on 2021-12-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_calibrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calibrator',
            name='comments',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
